import json
import sys
import os
import traceback
from celery import Celery
from WAPP_MODULE.WindowsForensicArtefactParser import WindowsForensicArtefactParser
from LAPP_MODULE.LinuxForensicArtefactParser import LinuxForensicArtefactParser

SHARED_FOLDER_PATH = "/python-docker/shared_files/"
DEPOT_FOLDER_PATH = os.environ.get("API_DEPOT_FOLDER_PATH", os.path.join(SHARED_FOLDER_PATH, "depot"))

raw_bulk_path = os.environ.get("BULK_DEPOT_FOLDER_PATH", "")
if raw_bulk_path:
    # If the user specified a full host path like /home/user/.../shared_files/bulk_ingest,
    # extract the part after shared_files/ so it stays inside the mounted docker volume
    if "shared_files/" in raw_bulk_path:
        sub_path = raw_bulk_path.split("shared_files/")[-1]
        BULK_DEPOT_FOLDER_PATH = os.path.join(SHARED_FOLDER_PATH, sub_path)
    elif not raw_bulk_path.startswith("/python-docker/"):
        BULK_DEPOT_FOLDER_PATH = os.path.join(SHARED_FOLDER_PATH, raw_bulk_path.lstrip("/"))
    else:
        BULK_DEPOT_FOLDER_PATH = raw_bulk_path
else:
    BULK_DEPOT_FOLDER_PATH = os.path.join(SHARED_FOLDER_PATH, "bulk_depot")

# Automatic directory creation inside mounted volume
os.makedirs(DEPOT_FOLDER_PATH, exist_ok=True)
os.makedirs(BULK_DEPOT_FOLDER_PATH, exist_ok=True)

WORKING_FOLDER_PATH = os.path.join(SHARED_FOLDER_PATH, "work")
LOG_FOLDER_PATH = os.path.join(WORKING_FOLDER_PATH, "execution_logs")
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379')
celery = Celery('tasks', broker=CELERY_BROKER_URL, backend=CELERY_RESULT_BACKEND)

@celery.task(queue='parse')
def parse_archive(content, file_name):
    """
     Celery Tasks function "parse_archive" which will parse an archive generated by DFIR-ORC.

    :param content: parameters of the request
    :type content: dict
    :param file_name: file name of the file which was uploaded
    :type file_name: str
    :return: message telling the result of the analysis
    :rtype: str
    """

    try:
        main_id = parse_archive.request.id
        if content.get("archiveType", "") == "UAC":
            #return {"taskId": "{}".format(parse_archive.request.id), "WokerStatus": "Failled", "Message": "UAC parser is not available for now"}
            return parse_uac(main_id, content, file_name)
        else:
            return parse_orc(main_id, content, file_name)

    except Exception as ex:

        sys.stderr.write("\nerror : {}\n".format(traceback.format_exc()))
        return {"taskId": "{}".format(parse_archive.request.id), "WokerStatus": "Failled"}

def get_machine_name(content_data, archive_file_name):
    machine_name = ""
    if content_data.get("machineName", ""):
        machine_name = content_data.get("machineName")
    elif "DFIR-ORC_" in archive_file_name:
        machine_name = os.path.splitext(archive_file_name.replace("DFIR-ORC_", ""))[0]
    else:
        machine_name = os.path.splitext(archive_file_name)[0]
    return machine_name

def parse_orc(main_id, content, file_name):
    """
     Celery Tasks function "parse_archive" which will parse an archive generated by DFIR-ORC.
    :param main_id: id of the celery worker tasks
    :type content: str
    :param content: parameters of the request
    :type content: dict
    :param file_name: file name of the file which was uploaded
    :type file_name: str
    :return: message telling the result of the analysis
    :rtype: str
    """

    try:
        source_folder = content.get("source_folder", DEPOT_FOLDER_PATH)
        archive_path = os.path.join(source_folder, file_name)
        case_name = content.get("caseName", "")
        machine_name = content.get("machineName", "No_Name")
        parser_config = content.get('parser_config', None)
        artefact_config = content.get('artefact_config', None)
        if content.get("archiveType", "") == "ORC":
            is_orc = True
        else:
            is_orc = False

        print(json.dumps(content, indent=4))


        wapp_parser = WindowsForensicArtefactParser(path_to_archive=archive_path,
                                                    output_directory=WORKING_FOLDER_PATH,
                                                    case_name=case_name,
                                                    machine_name=machine_name,
                                                    separator="|",
                                                    main_id=main_id,
                                                    artefact_config=artefact_config,
                                                    main_config=parser_config,
                                                    is_orc = is_orc)

        wapp_parser.do()

        return {"taskId": "{}".format(main_id), "WokerStatus": "finished"}

    except Exception as ex:

        sys.stderr.write("\nerror : {}\n".format(traceback.format_exc()))
        return {"taskId": "{}".format(parse_archive.request.id), "WokerStatus": "Failled"}

def parse_uac(main_id, content, file_name):
    """
     Celery Tasks function "parse_archive" which will parse an archive generated by DFIR-ORC.
    :param main_id: id of the celery worker tasks
    :type content: str
    :param content: parameters of the request
    :type content: dict
    :param file_name: file name of the file which was uploaded
    :type file_name: str
    :return: message telling the result of the analysis
    :rtype: str
    """

    try:
        source_folder = content.get("source_folder", DEPOT_FOLDER_PATH)
        archive_path = os.path.join(source_folder, file_name)
        case_name = content.get("caseName", "")
        machine_name = content.get("machineName", "No_Name")

        lapp_parser = LinuxForensicArtefactParser(path_to_archive=archive_path,
                                                  output_directory=WORKING_FOLDER_PATH,
                                                  case_name=case_name,
                                                  machine_name=machine_name,
                                                  separator="|",
                                                  main_id=main_id)

        lapp_parser.do()

        return {"taskId": "{}".format(main_id), "WokerStatus": "finished"}

    except Exception as ex:

        sys.stderr.write("\nerror : {}\n".format(traceback.format_exc()))
        return {"taskId": "{}".format(parse_archive.request.id), "WokerStatus": "Failled"}
