import re
from pathlib import Path

from ..classes.BaseArtefactPipelines import BaseArtefactPipeline
from ..classes.WappContext import WappContext
from ..classes.Registry import register_pipeline

@register_pipeline(name="orc")
class OrcLogPipeline(BaseArtefactPipeline):
    """
    Parses specific artifacts generated by DFIR-ORC.
    """
    recommended = True
    DEFAULT_PATTERNS = {"orc_run_logs": ["Statistics.json", "config.xml", "Config.xml", "FastFind_result.xml", "Statistics_*.json", "_config.xml", "Artefacts.log", "VSS_list.log", "Browsers_artefacts.log", "UserHives.log", "autoruns.log", "MFT.log", "SystemHives.log", "Event.log", "processes2.log", "TextLogs.log", "AD_computers.log", "SAM.log", "DNS_records.log", "TextLogs", "Browsers_history.log", "EventConsumer.log", "USNInfo.log", "processes1.log"]}

    def __init__(self, context: WappContext):
        super().__init__(context)
        self.out_log_dir = self.context.parsed_dir / "orcLogs"
        self.out_dir = self.context.result_parsed_dir
        self.out_log_dir.mkdir(exist_ok=True)

    def process(self, file_path: Path):
        self.logger.info(f"[PIPELINE][ORCLOGS] Processing {file_path.name}", header="START", indentation=1)
        try:
            if not self.can_process(file_path):
                return
                
            for reg_pattern in self.get_regex_patterns():
                if re.search(reg_pattern, file_path.name, re.IGNORECASE):
                    self.copy_raw_artefact(file_path, self.out_log_dir)
                    break
                    
            self.logger.info(f"[PIPELINE][ORCLOGS] Success", header="FINISHED", indentation=1)
        except Exception as e:
            self.logger.error(f"[PIPELINE][ORCLOGS] Error on {file_path.name}: {e}", header="ERROR", indentation=1)