import csv
import os
import re
from pathlib import Path

from .WappContext import WappContext


class OrcRenamer:
    """
    Pre-processor responsible for renaming artifacts extracted by DFIR-ORC.
    It prioritizes 'GetThis*.csv' files to find the exact original name.
    If it fails, it uses a fallback based on regular expressions.
    """

    def __init__(self, context: WappContext):
        self.context = context
        self.logger = context.logger
        self.mapping = {}

    def build_mapping(self, extracted_dir: Path):
        """
        Traverses the directory tree looking for all GetThis log files
        (even in subfolders) to build a global dictionary.
        """
        # Robust search for all GetThis files in all subfolders
        getthis_files = [f for f in extracted_dir.rglob("*.csv") if "GetThis" in f.name]

        for csv_file in getthis_files:
            try:
                with open(csv_file, 'r', encoding='utf-8', errors='ignore') as f:
                    reader = csv.DictReader(f)
                    for row in reader:
                        sample_name = row.get("SampleName")
                        full_name = row.get("FullName")

                        if sample_name and full_name:
                            # CRITICAL: ORC generates Windows paths (\). If the script runs under
                            # Linux/Docker, Path().name will not work. We force manual split.
                            ugly_basename = sample_name.replace('\\', '/').split('/')[-1]
                            clean_basename = full_name.replace('\\', '/').split('/')[-1]

                            # Store in mapping
                            self.mapping[ugly_basename] = clean_basename
            except Exception as e:
                self.logger.error(f"[RENAMER] Error reading {csv_file.name}: {e}", header="ERROR",
                                  indentation=1)

    def rename_with_getthis(self, extracted_dir: Path):
        """
        Traverses all extracted files and renames them via GetThis mapping.
        """
        self.logger.info("[RENAMER] GetThis mode enabled. Building mapping (slow)...", header="START", indentation=1)
        self.build_mapping(extracted_dir)
        self.logger.info(f"[RENAMER] {len(self.mapping)} exact matches found in GetThis logs",
                         header="INFO", indentation=1)

        renamed_count = 0

        for file_path in extracted_dir.rglob("*"):
            if not file_path.is_file():
                continue

            original_name = file_path.name
            
            # Ignore system files generated by ORC
            if original_name.endswith(".csv") and "GetThis" in original_name:
                continue

            if original_name in self.mapping:
                new_name = self.mapping[original_name]
                new_path = file_path.parent / new_name

                # Collision management (multiple files with the same final name)
                counter = 1
                while new_path.exists() and new_path != file_path:
                    new_path = file_path.parent / f"{Path(new_name).stem}_{counter}{Path(new_name).suffix}"
                    counter += 1

                try:
                    file_path.rename(new_path)
                    renamed_count += 1
                except Exception as e:
                    self.logger.warning(f"[RENAMER] Failed to rename {original_name} to {new_name}: {e}",
                                        header="WARNING", indentation=2)

        self.logger.info(f"[RENAMER] GetThis renaming completed. {renamed_count} files renamed.",
                         header="FINISHED")

    def rename_with_regex(self, extracted_dir: Path):
        """
        Traverses all extracted files and renames them with ultra-fast regex.
        """
        self.logger.info("[RENAMER] Starting Regex renaming (ultra-fast)", header="START", indentation=1)

        renamed_count = 0

        for file_path in extracted_dir.rglob("*"):
            if not file_path.is_file():
                continue

            original_name = file_path.name
            
            if original_name.endswith(".csv") and "GetThis" in original_name:
                continue

            new_name = self._clean_regex(original_name)

            if new_name and new_name != original_name:
                new_path = file_path.parent / new_name

                counter = 1
                while new_path.exists() and new_path != file_path:
                    new_path = file_path.parent / f"{Path(new_name).stem}_{counter}{Path(new_name).suffix}"
                    counter += 1

                try:
                    file_path.rename(new_path)
                    renamed_count += 1
                except Exception as e:
                    self.logger.warning(f"[RENAMER] Failed to rename {original_name} to {new_name}: {e}",
                                        header="WARNING", indentation=2)

        self.logger.info(f"[RENAMER] Regex renaming completed. {renamed_count} files cleanly renamed.",
                         header="FINISHED")

    def _clean_regex(self, filename: str) -> str:
        """
        Improved Regex fallback to clean names if GetThis.csv is missing.
        Handles ORC pattern: VolumeID_ParentFRN_FRN_AttributeID_OriginalName_{GUID}.data
        """
        l_file_to_preserve = ["USNInfo", "NTFSInfo", "GetThis"]

        for f in l_file_to_preserve:
            if f in filename:
                return filename

        # 1. Clean ORC suffix ({GUID}.data)
        filename_clean = re.sub(r'_\{[a-fA-F0-9\-]+\}(?:\.data)?$', '', filename)
        filename_clean = re.sub(r'\_data$', '', filename_clean)

        # 2. Clean ORC prefixes (3 or 4 hex/num blocks separated by _)
        # Ex: BEB0FD2161F2A88F_1000000000D33_80000000105C1_4_
        filename_clean = re.sub(r'^([A-Fa-f0-9]{5,20}_){2,4}(?:[A-Fa-f0-9]+_)?', '', filename_clean)

        return filename_clean if filename_clean else filename