import json
from pathlib import Path
from typing import Generator, Dict, Any, Tuple
from ...classes.BaseParser import BaseParser

class OgreParser(BaseParser):
    """
    Parses JSONL files generated by DFIR-Ogre.
    """
    def parse(self, input_path: Path) -> Generator[Tuple[str, Dict[str, Any]], None, None]:
        parts = input_path.name.split('.')
        if len(parts) >= 2 and parts[-1] == 'jsonl':
            mapping_label = parts[-2]
        else:
            mapping_label = input_path.parent.name

        with open(input_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                    timestamp_raw = event.get("timestamp", "")
                    date_part, time_part = "", ""
                    if "T" in timestamp_raw:
                        date_part, time_part = timestamp_raw.split("T", 1)
                        if "+" in time_part:
                            time_part = time_part.split("+")[0]
                        elif "-" in time_part:
                            time_part = time_part.split("-")[0]
                        elif "Z" in time_part:
                            time_part = time_part.replace("Z", "")
                    
                    data_dict = {
                        "date": date_part,
                        "time": time_part,
                        "description": event.get("description", ""),
                        "additional_description": event.get("additional_description", "")
                    }
                    
                    yield f"ogre_{mapping_label}", data_dict
                except json.JSONDecodeError:
                    continue

